### ISSUE TITLE
Openssl check fails for current versions of openssl

### ISSUE THREAD

**Issue by mhthies** [jackbenny/check_imap_starttls#1]
`openssl -h` returns *Invalid command '-h'; type "help" for a list.* and exit code 1 on my Debian Buster machine (OpenSSL 1.1.1d). Thus, the command for checking openssl should be changed to `openssl help`.

**Comment by jackbenny** [comment]
Thank you for pointing this out! Much appreciated! I have fixed it now, and committed the changes.
